name: "build"

on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: test shell
        run: devenv test

      - name: pytest
        run: devenv shell uv run pytest

      # TODO
      # - [ ] Use OIDC to authenticate with AWS
      #       https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      # - [ ] Figure out how to choose the environment to deploy to

      # - name: "Configure AWS credentials"
      #   uses: "aws-actions/configure-aws-credentials@v4"
      #   with:
      #     aws-access-key-id: "${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}"
      #     aws-secret-access-key: "${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}"
      #     aws-region: "${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}"

      # - name: deploy
      #   run: devenv shell ./deploy.sh
